# Generated by Django 3.2.2 on 2021-05-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_staff_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=80)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cont_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
