# Generated by Django 3.2.2 on 2021-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='potato', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
